# Generated by Django 3.2 on 2021-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_quereies_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quereies",
            name="image",
            field=models.ImageField(upload_to="api/classifier"),
        ),
    ]
